# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.vlayout_left = QtWidgets.QVBoxLayout()
        self.vlayout_left.setObjectName("vlayout_left")
        self.grp_file = QtWidgets.QGroupBox(self.centralwidget)
        self.grp_file.setObjectName("grp_file")
        self.gridLayout = QtWidgets.QGridLayout(self.grp_file)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_file_drop = FileDropLabel(self.grp_file)
        self.lbl_file_drop.setAcceptDrops(True)
        self.lbl_file_drop.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_file_drop.setObjectName("lbl_file_drop")
        self.gridLayout.addWidget(self.lbl_file_drop, 0, 0, 1, 1)
        self.vlayout_left.addWidget(self.grp_file)
        self.grp_intervals = QtWidgets.QGroupBox(self.centralwidget)
        self.grp_intervals.setObjectName("grp_intervals")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.grp_intervals)
        self.verticalLayout.setObjectName("verticalLayout")
        self.glayout_intervals = QtWidgets.QGridLayout()
        self.glayout_intervals.setObjectName("glayout_intervals")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.glayout_intervals.addItem(spacerItem, 4, 1, 1, 1)
        self.tbtn_move_up = QtWidgets.QToolButton(self.grp_intervals)
        self.tbtn_move_up.setObjectName("tbtn_move_up")
        self.glayout_intervals.addWidget(self.tbtn_move_up, 0, 1, 1, 1)
        self.tbtn_remove = QtWidgets.QToolButton(self.grp_intervals)
        self.tbtn_remove.setObjectName("tbtn_remove")
        self.glayout_intervals.addWidget(self.tbtn_remove, 2, 1, 1, 1)
        self.tbtn_move_down = QtWidgets.QToolButton(self.grp_intervals)
        self.tbtn_move_down.setObjectName("tbtn_move_down")
        self.glayout_intervals.addWidget(self.tbtn_move_down, 1, 1, 1, 1)
        self.tbtn_clear = QtWidgets.QToolButton(self.grp_intervals)
        self.tbtn_clear.setObjectName("tbtn_clear")
        self.glayout_intervals.addWidget(self.tbtn_clear, 3, 1, 1, 1)
        self.tabv_intervals = QtWidgets.QTableView(self.grp_intervals)
        self.tabv_intervals.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tabv_intervals.setObjectName("tabv_intervals")
        self.glayout_intervals.addWidget(self.tabv_intervals, 0, 0, 5, 1)
        self.verticalLayout.addLayout(self.glayout_intervals)
        self.hlayout_add_interval = QtWidgets.QHBoxLayout()
        self.hlayout_add_interval.setObjectName("hlayout_add_interval")
        self.flayout_add_interval = QtWidgets.QFormLayout()
        self.flayout_add_interval.setObjectName("flayout_add_interval")
        self.lbl_interval_begin = QtWidgets.QLabel(self.grp_intervals)
        self.lbl_interval_begin.setObjectName("lbl_interval_begin")
        self.flayout_add_interval.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_interval_begin)
        self.hlayout_add_interval_begin = QtWidgets.QHBoxLayout()
        self.hlayout_add_interval_begin.setObjectName("hlayout_add_interval_begin")
        self.spin_interval_begin_hour = QtWidgets.QSpinBox(self.grp_intervals)
        self.spin_interval_begin_hour.setMaximum(999999999)
        self.spin_interval_begin_hour.setObjectName("spin_interval_begin_hour")
        self.hlayout_add_interval_begin.addWidget(self.spin_interval_begin_hour)
        self.lbl_colon_0 = QtWidgets.QLabel(self.grp_intervals)
        self.lbl_colon_0.setObjectName("lbl_colon_0")
        self.hlayout_add_interval_begin.addWidget(self.lbl_colon_0)
        self.spin_interval_begin_mins = QtWidgets.QSpinBox(self.grp_intervals)
        self.spin_interval_begin_mins.setMaximum(59)
        self.spin_interval_begin_mins.setObjectName("spin_interval_begin_mins")
        self.hlayout_add_interval_begin.addWidget(self.spin_interval_begin_mins)
        self.lbl_colon_1 = QtWidgets.QLabel(self.grp_intervals)
        self.lbl_colon_1.setObjectName("lbl_colon_1")
        self.hlayout_add_interval_begin.addWidget(self.lbl_colon_1)
        self.spin_interval_begin_secs = QtWidgets.QSpinBox(self.grp_intervals)
        self.spin_interval_begin_secs.setMaximum(59)
        self.spin_interval_begin_secs.setObjectName("spin_interval_begin_secs")
        self.hlayout_add_interval_begin.addWidget(self.spin_interval_begin_secs)
        self.flayout_add_interval.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.hlayout_add_interval_begin)
        self.lbl_interval_end = QtWidgets.QLabel(self.grp_intervals)
        self.lbl_interval_end.setObjectName("lbl_interval_end")
        self.flayout_add_interval.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_interval_end)
        self.hlayout_add_interval_end = QtWidgets.QHBoxLayout()
        self.hlayout_add_interval_end.setObjectName("hlayout_add_interval_end")
        self.spin_interval_end_hour = QtWidgets.QSpinBox(self.grp_intervals)
        self.spin_interval_end_hour.setMaximum(999999999)
        self.spin_interval_end_hour.setObjectName("spin_interval_end_hour")
        self.hlayout_add_interval_end.addWidget(self.spin_interval_end_hour)
        self.lbl_colon_2 = QtWidgets.QLabel(self.grp_intervals)
        self.lbl_colon_2.setObjectName("lbl_colon_2")
        self.hlayout_add_interval_end.addWidget(self.lbl_colon_2)
        self.spin_interval_end_mins = QtWidgets.QSpinBox(self.grp_intervals)
        self.spin_interval_end_mins.setMaximum(59)
        self.spin_interval_end_mins.setObjectName("spin_interval_end_mins")
        self.hlayout_add_interval_end.addWidget(self.spin_interval_end_mins)
        self.lbl_colon_3 = QtWidgets.QLabel(self.grp_intervals)
        self.lbl_colon_3.setObjectName("lbl_colon_3")
        self.hlayout_add_interval_end.addWidget(self.lbl_colon_3)
        self.spin_interval_end_secs = QtWidgets.QSpinBox(self.grp_intervals)
        self.spin_interval_end_secs.setMaximum(59)
        self.spin_interval_end_secs.setObjectName("spin_interval_end_secs")
        self.hlayout_add_interval_end.addWidget(self.spin_interval_end_secs)
        self.flayout_add_interval.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.hlayout_add_interval_end)
        self.hlayout_add_interval.addLayout(self.flayout_add_interval)
        self.pbtn_add_interval = QtWidgets.QPushButton(self.grp_intervals)
        self.pbtn_add_interval.setObjectName("pbtn_add_interval")
        self.hlayout_add_interval.addWidget(self.pbtn_add_interval)
        self.verticalLayout.addLayout(self.hlayout_add_interval)
        self.vlayout_left.addWidget(self.grp_intervals)
        self.vlayout_left.setStretch(0, 1)
        self.vlayout_left.setStretch(1, 3)
        self.horizontalLayout_2.addLayout(self.vlayout_left)
        self.vlayout_right = QtWidgets.QVBoxLayout()
        self.vlayout_right.setObjectName("vlayout_right")
        self.grp_source = QtWidgets.QGroupBox(self.centralwidget)
        self.grp_source.setObjectName("grp_source")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.grp_source)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(290, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        self.tbtn_parse_source = QtWidgets.QToolButton(self.grp_source)
        self.tbtn_parse_source.setObjectName("tbtn_parse_source")
        self.gridLayout_2.addWidget(self.tbtn_parse_source, 1, 2, 1, 1)
        self.txtedt_source = QtWidgets.QTextEdit(self.grp_source)
        self.txtedt_source.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.txtedt_source.setObjectName("txtedt_source")
        self.gridLayout_2.addWidget(self.txtedt_source, 0, 0, 1, 3)
        self.chkbox_format_source = QtWidgets.QCheckBox(self.grp_source)
        self.chkbox_format_source.setObjectName("chkbox_format_source")
        self.gridLayout_2.addWidget(self.chkbox_format_source, 1, 1, 1, 1)
        self.vlayout_right.addWidget(self.grp_source)
        self.grp_output = QtWidgets.QGroupBox(self.centralwidget)
        self.grp_output.setObjectName("grp_output")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.grp_output)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_output_path = QtWidgets.QLabel(self.grp_output)
        self.lbl_output_path.setObjectName("lbl_output_path")
        self.horizontalLayout.addWidget(self.lbl_output_path)
        self.lineedt_output_path = QtWidgets.QLineEdit(self.grp_output)
        self.lineedt_output_path.setObjectName("lineedt_output_path")
        self.horizontalLayout.addWidget(self.lineedt_output_path)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.txtbrw_output = QtWidgets.QTextBrowser(self.grp_output)
        self.txtbrw_output.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.txtbrw_output.setObjectName("txtbrw_output")
        self.verticalLayout_3.addWidget(self.txtbrw_output)
        self.vlayout_right.addWidget(self.grp_output)
        self.horizontalLayout_2.addLayout(self.vlayout_right)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menuBar.setObjectName("menuBar")
        self.menu_T = QtWidgets.QMenu(self.menuBar)
        self.menu_T.setObjectName("menu_T")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.act_new_task = QtWidgets.QAction(MainWindow)
        self.act_new_task.setObjectName("act_new_task")
        self.menu_T.addAction(self.act_new_task)
        self.menuBar.addAction(self.menu_T.menuAction())

        self.retranslateUi(MainWindow)
        self.spin_interval_begin_hour.valueChanged['int'].connect(MainWindow.on_spin_interval_begin_value_changed)
        self.spin_interval_begin_mins.valueChanged['int'].connect(MainWindow.on_spin_interval_begin_value_changed)
        self.spin_interval_begin_secs.valueChanged['int'].connect(MainWindow.on_spin_interval_begin_value_changed)
        self.spin_interval_end_hour.valueChanged['int'].connect(MainWindow.on_spin_interval_end_value_changed)
        self.spin_interval_end_mins.valueChanged['int'].connect(MainWindow.on_spin_interval_end_value_changed)
        self.spin_interval_end_secs.valueChanged['int'].connect(MainWindow.on_spin_interval_end_value_changed)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabv_intervals, self.spin_interval_begin_hour)
        MainWindow.setTabOrder(self.spin_interval_begin_hour, self.spin_interval_begin_mins)
        MainWindow.setTabOrder(self.spin_interval_begin_mins, self.spin_interval_begin_secs)
        MainWindow.setTabOrder(self.spin_interval_begin_secs, self.spin_interval_end_hour)
        MainWindow.setTabOrder(self.spin_interval_end_hour, self.spin_interval_end_mins)
        MainWindow.setTabOrder(self.spin_interval_end_mins, self.spin_interval_end_secs)
        MainWindow.setTabOrder(self.spin_interval_end_secs, self.pbtn_add_interval)
        MainWindow.setTabOrder(self.pbtn_add_interval, self.tbtn_move_up)
        MainWindow.setTabOrder(self.tbtn_move_up, self.tbtn_move_down)
        MainWindow.setTabOrder(self.tbtn_move_down, self.tbtn_remove)
        MainWindow.setTabOrder(self.tbtn_remove, self.txtedt_source)
        MainWindow.setTabOrder(self.txtedt_source, self.txtbrw_output)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "小工具-ffmpeg无损剪辑命令产生器"))
        self.grp_file.setTitle(_translate("MainWindow", "选定文件"))
        self.lbl_file_drop.setText(_translate("MainWindow", "将待剪辑的文件拖到这里即可选定文件"))
        self.grp_intervals.setTitle(_translate("MainWindow", "时间段列表"))
        self.tbtn_move_up.setText(_translate("MainWindow", "上移"))
        self.tbtn_remove.setText(_translate("MainWindow", "删除"))
        self.tbtn_move_down.setText(_translate("MainWindow", "下移"))
        self.tbtn_clear.setText(_translate("MainWindow", "清空"))
        self.lbl_interval_begin.setText(_translate("MainWindow", "开始时间"))
        self.lbl_colon_0.setText(_translate("MainWindow", ":"))
        self.lbl_colon_1.setText(_translate("MainWindow", ":"))
        self.lbl_interval_end.setText(_translate("MainWindow", "截止时间"))
        self.lbl_colon_2.setText(_translate("MainWindow", ":"))
        self.lbl_colon_3.setText(_translate("MainWindow", ":"))
        self.pbtn_add_interval.setText(_translate("MainWindow", "增加一个时间段"))
        self.pbtn_add_interval.setShortcut(_translate("MainWindow", "Ctrl+Return"))
        self.grp_source.setTitle(_translate("MainWindow", "源码预览/导入源码"))
        self.tbtn_parse_source.setText(_translate("MainWindow", "解析源码"))
        self.chkbox_format_source.setText(_translate("MainWindow", "格式化源码"))
        self.grp_output.setTitle(_translate("MainWindow", "输出命令"))
        self.lbl_output_path.setText(_translate("MainWindow", "视频输出路径"))
        self.menu_T.setTitle(_translate("MainWindow", "任务(&T)"))
        self.act_new_task.setText(_translate("MainWindow", "新建任务"))
        self.act_new_task.setShortcut(_translate("MainWindow", "Ctrl+N"))
from ui.FileDropLabel import FileDropLabel
