# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.grp_file = QtWidgets.QGroupBox(self.centralwidget)
        self.grp_file.setObjectName("grp_file")
        self.gridLayout = QtWidgets.QGridLayout(self.grp_file)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_file_drop = FileDropLabel(self.grp_file)
        self.lbl_file_drop.setAcceptDrops(True)
        self.lbl_file_drop.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_file_drop.setObjectName("lbl_file_drop")
        self.gridLayout.addWidget(self.lbl_file_drop, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.grp_file)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.grp_intervals = QtWidgets.QGroupBox(self.centralwidget)
        self.grp_intervals.setObjectName("grp_intervals")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.grp_intervals)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tbtn_move_up = QtWidgets.QToolButton(self.grp_intervals)
        self.tbtn_move_up.setObjectName("tbtn_move_up")
        self.gridLayout_2.addWidget(self.tbtn_move_up, 0, 0, 1, 1)
        self.tabv_intervals = QtWidgets.QTableView(self.grp_intervals)
        self.tabv_intervals.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tabv_intervals.setObjectName("tabv_intervals")
        self.gridLayout_2.addWidget(self.tabv_intervals, 0, 1, 5, 1)
        self.tbtn_move_down = QtWidgets.QToolButton(self.grp_intervals)
        self.tbtn_move_down.setObjectName("tbtn_move_down")
        self.gridLayout_2.addWidget(self.tbtn_move_down, 1, 0, 1, 1)
        self.tbtn_remove = QtWidgets.QToolButton(self.grp_intervals)
        self.tbtn_remove.setObjectName("tbtn_remove")
        self.gridLayout_2.addWidget(self.tbtn_remove, 2, 0, 1, 1)
        self.tbtn_clear = QtWidgets.QToolButton(self.grp_intervals)
        self.tbtn_clear.setObjectName("tbtn_clear")
        self.gridLayout_2.addWidget(self.tbtn_clear, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 4, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.hlayout_add_interval = QtWidgets.QHBoxLayout()
        self.hlayout_add_interval.setObjectName("hlayout_add_interval")
        self.flayout_add_interval = QtWidgets.QFormLayout()
        self.flayout_add_interval.setObjectName("flayout_add_interval")
        self.lbl_interval_begin = QtWidgets.QLabel(self.grp_intervals)
        self.lbl_interval_begin.setObjectName("lbl_interval_begin")
        self.flayout_add_interval.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_interval_begin)
        self.hlayout_add_interval_begin = QtWidgets.QHBoxLayout()
        self.hlayout_add_interval_begin.setObjectName("hlayout_add_interval_begin")
        self.spin_interval_begin_hour = QtWidgets.QSpinBox(self.grp_intervals)
        self.spin_interval_begin_hour.setMaximum(999999999)
        self.spin_interval_begin_hour.setObjectName("spin_interval_begin_hour")
        self.hlayout_add_interval_begin.addWidget(self.spin_interval_begin_hour)
        self.lbl_colon_0 = QtWidgets.QLabel(self.grp_intervals)
        self.lbl_colon_0.setObjectName("lbl_colon_0")
        self.hlayout_add_interval_begin.addWidget(self.lbl_colon_0)
        self.spin_interval_begin_mins = QtWidgets.QSpinBox(self.grp_intervals)
        self.spin_interval_begin_mins.setMaximum(59)
        self.spin_interval_begin_mins.setObjectName("spin_interval_begin_mins")
        self.hlayout_add_interval_begin.addWidget(self.spin_interval_begin_mins)
        self.lbl_colon_1 = QtWidgets.QLabel(self.grp_intervals)
        self.lbl_colon_1.setObjectName("lbl_colon_1")
        self.hlayout_add_interval_begin.addWidget(self.lbl_colon_1)
        self.spin_interval_begin_secs = QtWidgets.QSpinBox(self.grp_intervals)
        self.spin_interval_begin_secs.setMaximum(59)
        self.spin_interval_begin_secs.setObjectName("spin_interval_begin_secs")
        self.hlayout_add_interval_begin.addWidget(self.spin_interval_begin_secs)
        self.flayout_add_interval.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.hlayout_add_interval_begin)
        self.lbl_interval_end = QtWidgets.QLabel(self.grp_intervals)
        self.lbl_interval_end.setObjectName("lbl_interval_end")
        self.flayout_add_interval.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_interval_end)
        self.hlayout_add_interval_end = QtWidgets.QHBoxLayout()
        self.hlayout_add_interval_end.setObjectName("hlayout_add_interval_end")
        self.spin_interval_end_hour = QtWidgets.QSpinBox(self.grp_intervals)
        self.spin_interval_end_hour.setMaximum(999999999)
        self.spin_interval_end_hour.setObjectName("spin_interval_end_hour")
        self.hlayout_add_interval_end.addWidget(self.spin_interval_end_hour)
        self.lbl_colon_2 = QtWidgets.QLabel(self.grp_intervals)
        self.lbl_colon_2.setObjectName("lbl_colon_2")
        self.hlayout_add_interval_end.addWidget(self.lbl_colon_2)
        self.spin_interval_end_mins = QtWidgets.QSpinBox(self.grp_intervals)
        self.spin_interval_end_mins.setMaximum(59)
        self.spin_interval_end_mins.setObjectName("spin_interval_end_mins")
        self.hlayout_add_interval_end.addWidget(self.spin_interval_end_mins)
        self.lbl_colon_3 = QtWidgets.QLabel(self.grp_intervals)
        self.lbl_colon_3.setObjectName("lbl_colon_3")
        self.hlayout_add_interval_end.addWidget(self.lbl_colon_3)
        self.spin_interval_end_secs = QtWidgets.QSpinBox(self.grp_intervals)
        self.spin_interval_end_secs.setMaximum(59)
        self.spin_interval_end_secs.setObjectName("spin_interval_end_secs")
        self.hlayout_add_interval_end.addWidget(self.spin_interval_end_secs)
        self.flayout_add_interval.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.hlayout_add_interval_end)
        self.hlayout_add_interval.addLayout(self.flayout_add_interval)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hlayout_add_interval.addItem(spacerItem1)
        self.pbtn_add_interval = QtWidgets.QPushButton(self.grp_intervals)
        self.pbtn_add_interval.setObjectName("pbtn_add_interval")
        self.hlayout_add_interval.addWidget(self.pbtn_add_interval)
        self.verticalLayout.addLayout(self.hlayout_add_interval)
        self.verticalLayout_4.addWidget(self.grp_intervals)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_3.setObjectName("formLayout_3")
        self.lbl_filename = QtWidgets.QLabel(self.groupBox)
        self.lbl_filename.setObjectName("lbl_filename")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_filename)
        self.ledt_src_filename = QtWidgets.QLineEdit(self.groupBox)
        self.ledt_src_filename.setObjectName("ledt_src_filename")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ledt_src_filename)
        self.lbl_src_dir = QtWidgets.QLabel(self.groupBox)
        self.lbl_src_dir.setObjectName("lbl_src_dir")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_src_dir)
        self.ledt_src_path_dir = QtWidgets.QLineEdit(self.groupBox)
        self.ledt_src_path_dir.setObjectName("ledt_src_path_dir")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ledt_src_path_dir)
        self.horizontalLayout.addWidget(self.groupBox)
        self.grp_output = QtWidgets.QGroupBox(self.centralwidget)
        self.grp_output.setObjectName("grp_output")
        self.formLayout_2 = QtWidgets.QFormLayout(self.grp_output)
        self.formLayout_2.setObjectName("formLayout_2")
        self.lbl_dst_dir = QtWidgets.QLabel(self.grp_output)
        self.lbl_dst_dir.setObjectName("lbl_dst_dir")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_dst_dir)
        self.ledt_dst_path_dir = QtWidgets.QLineEdit(self.grp_output)
        self.ledt_dst_path_dir.setObjectName("ledt_dst_path_dir")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ledt_dst_path_dir)
        self.horizontalLayout.addWidget(self.grp_output)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.grp_meta = QtWidgets.QGroupBox(self.centralwidget)
        self.grp_meta.setObjectName("grp_meta")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.grp_meta)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.lbl_src_duration = QtWidgets.QLabel(self.grp_meta)
        self.lbl_src_duration.setObjectName("lbl_src_duration")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_src_duration)
        self.spin_src_duration = QtWidgets.QSpinBox(self.grp_meta)
        self.spin_src_duration.setReadOnly(True)
        self.spin_src_duration.setMaximum(999999999)
        self.spin_src_duration.setObjectName("spin_src_duration")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spin_src_duration)
        self.horizontalLayout_6.addLayout(self.formLayout)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.lbl_src_size = QtWidgets.QLabel(self.grp_meta)
        self.lbl_src_size.setObjectName("lbl_src_size")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_src_size)
        self.spin_src_size = QtWidgets.QDoubleSpinBox(self.grp_meta)
        self.spin_src_size.setReadOnly(True)
        self.spin_src_size.setDecimals(0)
        self.spin_src_size.setMaximum(1e+69)
        self.spin_src_size.setObjectName("spin_src_size")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spin_src_size)
        self.horizontalLayout_6.addLayout(self.formLayout_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.tbtn_src_meta_refresh = QtWidgets.QToolButton(self.grp_meta)
        self.tbtn_src_meta_refresh.setObjectName("tbtn_src_meta_refresh")
        self.horizontalLayout_3.addWidget(self.tbtn_src_meta_refresh)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_5.addWidget(self.grp_meta)
        self.grp_view = QtWidgets.QGroupBox(self.centralwidget)
        self.grp_view.setObjectName("grp_view")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.grp_view)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabw_view = QtWidgets.QTabWidget(self.grp_view)
        self.tabw_view.setObjectName("tabw_view")
        self.tab_commands = QtWidgets.QWidget()
        self.tab_commands.setObjectName("tab_commands")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_commands)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.txtbrw_output = QtWidgets.QTextBrowser(self.tab_commands)
        self.txtbrw_output.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.txtbrw_output.setObjectName("txtbrw_output")
        self.verticalLayout_6.addWidget(self.txtbrw_output)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.tbtn_refresh_commands = QtWidgets.QToolButton(self.tab_commands)
        self.tbtn_refresh_commands.setObjectName("tbtn_refresh_commands")
        self.horizontalLayout_4.addWidget(self.tbtn_refresh_commands)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.tabw_view.addTab(self.tab_commands, "")
        self.tab_source = QtWidgets.QWidget()
        self.tab_source.setObjectName("tab_source")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_source)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.txtbrw_source = QtWidgets.QTextBrowser(self.tab_source)
        self.txtbrw_source.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.txtbrw_source.setObjectName("txtbrw_source")
        self.verticalLayout_7.addWidget(self.txtbrw_source)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.tbtn_refresh_source = QtWidgets.QToolButton(self.tab_source)
        self.tbtn_refresh_source.setObjectName("tbtn_refresh_source")
        self.horizontalLayout_7.addWidget(self.tbtn_refresh_source)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.tabw_view.addTab(self.tab_source, "")
        self.verticalLayout_3.addWidget(self.tabw_view)
        self.verticalLayout_5.addWidget(self.grp_view)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menuBar.setObjectName("menuBar")
        self.menu_T = QtWidgets.QMenu(self.menuBar)
        self.menu_T.setObjectName("menu_T")
        self.menu_S = QtWidgets.QMenu(self.menuBar)
        self.menu_S.setObjectName("menu_S")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.act_file_new = QtWidgets.QAction(MainWindow)
        self.act_file_new.setObjectName("act_file_new")
        self.act_setting_format = QtWidgets.QAction(MainWindow)
        self.act_setting_format.setCheckable(True)
        self.act_setting_format.setChecked(True)
        self.act_setting_format.setObjectName("act_setting_format")
        self.act_file_open = QtWidgets.QAction(MainWindow)
        self.act_file_open.setObjectName("act_file_open")
        self.act_file_save = QtWidgets.QAction(MainWindow)
        self.act_file_save.setObjectName("act_file_save")
        self.act_file_save_as = QtWidgets.QAction(MainWindow)
        self.act_file_save_as.setObjectName("act_file_save_as")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.menu_T.addAction(self.act_file_new)
        self.menu_T.addAction(self.act_file_open)
        self.menu_T.addAction(self.act_file_save)
        self.menu_T.addAction(self.act_file_save_as)
        self.menu_S.addAction(self.act_setting_format)
        self.menuBar.addAction(self.menu_T.menuAction())
        self.menuBar.addAction(self.menu_S.menuAction())

        self.retranslateUi(MainWindow)
        self.tabw_view.setCurrentIndex(0)
        self.spin_interval_begin_hour.valueChanged['int'].connect(MainWindow.on_spin_interval_begin_value_changed)
        self.spin_interval_begin_mins.valueChanged['int'].connect(MainWindow.on_spin_interval_begin_value_changed)
        self.spin_interval_begin_secs.valueChanged['int'].connect(MainWindow.on_spin_interval_begin_value_changed)
        self.spin_interval_end_hour.valueChanged['int'].connect(MainWindow.on_spin_interval_end_value_changed)
        self.spin_interval_end_mins.valueChanged['int'].connect(MainWindow.on_spin_interval_end_value_changed)
        self.spin_interval_end_secs.valueChanged['int'].connect(MainWindow.on_spin_interval_end_value_changed)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.ledt_src_filename, self.ledt_src_path_dir)
        MainWindow.setTabOrder(self.ledt_src_path_dir, self.ledt_dst_path_dir)
        MainWindow.setTabOrder(self.ledt_dst_path_dir, self.spin_src_duration)
        MainWindow.setTabOrder(self.spin_src_duration, self.spin_src_size)
        MainWindow.setTabOrder(self.spin_src_size, self.tbtn_src_meta_refresh)
        MainWindow.setTabOrder(self.tbtn_src_meta_refresh, self.tbtn_move_up)
        MainWindow.setTabOrder(self.tbtn_move_up, self.tbtn_move_down)
        MainWindow.setTabOrder(self.tbtn_move_down, self.tbtn_remove)
        MainWindow.setTabOrder(self.tbtn_remove, self.tbtn_clear)
        MainWindow.setTabOrder(self.tbtn_clear, self.tabv_intervals)
        MainWindow.setTabOrder(self.tabv_intervals, self.spin_interval_begin_hour)
        MainWindow.setTabOrder(self.spin_interval_begin_hour, self.spin_interval_begin_mins)
        MainWindow.setTabOrder(self.spin_interval_begin_mins, self.spin_interval_begin_secs)
        MainWindow.setTabOrder(self.spin_interval_begin_secs, self.spin_interval_end_hour)
        MainWindow.setTabOrder(self.spin_interval_end_hour, self.spin_interval_end_mins)
        MainWindow.setTabOrder(self.spin_interval_end_mins, self.spin_interval_end_secs)
        MainWindow.setTabOrder(self.spin_interval_end_secs, self.pbtn_add_interval)
        MainWindow.setTabOrder(self.pbtn_add_interval, self.tabw_view)
        MainWindow.setTabOrder(self.tabw_view, self.txtbrw_output)
        MainWindow.setTabOrder(self.txtbrw_output, self.txtbrw_source)
        MainWindow.setTabOrder(self.txtbrw_source, self.tbtn_refresh_source)
        MainWindow.setTabOrder(self.tbtn_refresh_source, self.tbtn_refresh_commands)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "小工具-ffmpeg无损剪辑命令产生器"))
        self.grp_file.setTitle(_translate("MainWindow", "选定文件"))
        self.lbl_file_drop.setText(_translate("MainWindow", "将待剪辑的视频/其对应的JSON配置拖至此处"))
        self.grp_intervals.setTitle(_translate("MainWindow", "时间段列表"))
        self.tbtn_move_up.setText(_translate("MainWindow", "上移"))
        self.tbtn_move_up.setShortcut(_translate("MainWindow", "Ctrl+Alt+Up"))
        self.tbtn_move_down.setText(_translate("MainWindow", "下移"))
        self.tbtn_move_down.setShortcut(_translate("MainWindow", "Ctrl+Alt+Down"))
        self.tbtn_remove.setText(_translate("MainWindow", "删除"))
        self.tbtn_remove.setShortcut(_translate("MainWindow", "Del"))
        self.tbtn_clear.setText(_translate("MainWindow", "清空"))
        self.lbl_interval_begin.setText(_translate("MainWindow", "开始"))
        self.lbl_colon_0.setText(_translate("MainWindow", ":"))
        self.lbl_colon_1.setText(_translate("MainWindow", ":"))
        self.lbl_interval_end.setText(_translate("MainWindow", "截止"))
        self.lbl_colon_2.setText(_translate("MainWindow", ":"))
        self.lbl_colon_3.setText(_translate("MainWindow", ":"))
        self.pbtn_add_interval.setText(_translate("MainWindow", "增加该时间段"))
        self.pbtn_add_interval.setShortcut(_translate("MainWindow", "Ctrl+Return"))
        self.groupBox.setTitle(_translate("MainWindow", "输入参数"))
        self.lbl_filename.setText(_translate("MainWindow", "文件名称"))
        self.lbl_src_dir.setText(_translate("MainWindow", "所在目录"))
        self.grp_output.setTitle(_translate("MainWindow", "输出参数"))
        self.lbl_dst_dir.setText(_translate("MainWindow", "输出目录"))
        self.grp_meta.setTitle(_translate("MainWindow", "视频属性"))
        self.lbl_src_duration.setText(_translate("MainWindow", "视频时长"))
        self.spin_src_duration.setSuffix(_translate("MainWindow", " 毫秒"))
        self.lbl_src_size.setText(_translate("MainWindow", "视频大小"))
        self.spin_src_size.setSuffix(_translate("MainWindow", " 字节"))
        self.tbtn_src_meta_refresh.setText(_translate("MainWindow", "刷新数据"))
        self.grp_view.setTitle(_translate("MainWindow", "输出预览"))
        self.tbtn_refresh_commands.setText(_translate("MainWindow", "刷新"))
        self.tbtn_refresh_commands.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.tabw_view.setTabText(self.tabw_view.indexOf(self.tab_commands), _translate("MainWindow", "命令输出"))
        self.tbtn_refresh_source.setText(_translate("MainWindow", "刷新"))
        self.tbtn_refresh_source.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.tabw_view.setTabText(self.tabw_view.indexOf(self.tab_source), _translate("MainWindow", "源码预览"))
        self.menu_T.setTitle(_translate("MainWindow", "任务(&T)"))
        self.menu_S.setTitle(_translate("MainWindow", "设置(&S)"))
        self.act_file_new.setText(_translate("MainWindow", "新建文件"))
        self.act_file_new.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.act_setting_format.setText(_translate("MainWindow", "启用格式化"))
        self.act_file_open.setText(_translate("MainWindow", "打开文件"))
        self.act_file_open.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.act_file_save.setText(_translate("MainWindow", "保存文件"))
        self.act_file_save.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.act_file_save_as.setText(_translate("MainWindow", "另存为"))
        self.act_file_save_as.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.action_5.setText(_translate("MainWindow", "预览源码"))
        self.action_5.setShortcut(_translate("MainWindow", "Ctrl+R"))
from ui.FileDropLabel import FileDropLabel
